// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVejTYHF4O7l6v0ycZtjDF_O20l5kZCVg',
    appId: '1:711560282059:web:9c3992e47359fde53f804e',
    messagingSenderId: '711560282059',
    projectId: 'ecommerce-admin-panel-1ff6d',
    authDomain: 'ecommerce-admin-panel-1ff6d.firebaseapp.com',
    storageBucket: 'ecommerce-admin-panel-1ff6d.firebasestorage.app',
    measurementId: 'G-RDT7GSVLHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRvvBmeDFIKMx4Vg8u_zPGVf3pHhWV7L8',
    appId: '1:711560282059:android:f9cb99982b6929763f804e',
    messagingSenderId: '711560282059',
    projectId: 'ecommerce-admin-panel-1ff6d',
    storageBucket: 'ecommerce-admin-panel-1ff6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ9R5szvJ92hu0nPivxUi9rQ3TGykEjxs',
    appId: '1:711560282059:ios:57bd3dad54a4a9043f804e',
    messagingSenderId: '711560282059',
    projectId: 'ecommerce-admin-panel-1ff6d',
    storageBucket: 'ecommerce-admin-panel-1ff6d.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ9R5szvJ92hu0nPivxUi9rQ3TGykEjxs',
    appId: '1:711560282059:ios:8e46826b4ac6fd5a3f804e',
    messagingSenderId: '711560282059',
    projectId: 'ecommerce-admin-panel-1ff6d',
    storageBucket: 'ecommerce-admin-panel-1ff6d.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAdminPanel.RunnerTests',
  );
}
